### ISSUE TITLE
Browser crashes after some time

### ISSUE THREAD

**Issue by s134306** [LukeMurphey/splunk-slideshow#1]
Browser crashes after some time.

Every time when I use the slideshow app my browser crashes after some time. 

It was tested with Chrome and Firefox and with a 4 GB and  8GB RAM system. In the windows task manager the increasing consumption of RAM can be monitored.   

It was tested with an interval of 10 seconds (crash after ~10 minutes) and 5 minutes (crash after ~4 hours).

**Comment by LukeMurphey** [comment]
Thanks for the report. I'm looking into this.

**Comment by LukeMurphey** [comment]
I have this narrowed down; just trying to come up with the final fix. More details are available here: http://lukemurphey.net/issues/1148

**Comment by LukeMurphey** [comment]
This should be fixed in version 2.3.1. Memory is stable now.

**Comment by s134306** [comment]
Thanks for your fast help. For Firefox the issue is solved. With Chrome I have still the same issue.

**Comment by LukeMurphey** [comment]
Try clearing your cache. I'm pretty sure it is fixed on Chrome; I developed the workaround largely on Chrome and it fixed it for me.
