### ISSUE TITLE
How do I share my dashboards so they can be viewed in the slideshow

### ISSUE THREAD

**Issue by simon-k** [LukeMurphey/splunk-slideshow#3]
This is probably not the right place to ask this question, but I'll do it anyway.

The documentation for splunk-slideshow says that the dashboards should be shared for the slideshow to be able to show it. 

How do I share a dashboard?

**Comment by LukeMurphey** [comment]
Just click the option to edit the permission of the dashboard. Then set the sharing accordingly. Like this:

![sharing_dashboard](https://user-images.githubusercontent.com/1217581/38765267-0cb32dd8-3f84-11e8-96c5-578fabc5742b.gif)
